@hostname = http://localhost:8000
@tabla = products

GET {{hostname}}/{{tabla}}/5

###

#version basica
GET {{hostname}}/{{tabla}}/filter/precio?pricemin=20&pricemax=70

###

POST {{hostname}}/{{tabla}}/register
Content-Type: application/json

{
    "title": "Mouse Gamer",
    "price": 149.98,
    "quantity": 57,
    "status": 1
  }


###

PUT {{hostname}}/users/24
Content-Type: application/json

{
   "id": "24",
    "name": "Moises",
    "surname": "Perez",
    "age": 34,
    "mail": "moises@gmail.com",
    "status": 1,
    "password": "$2y$10$B2c3D4e5F6g7H8i9J0k1L",
    "rol": "user"
  }


###

  #comienzo auth
@ruta = auth
  ##

###

POST {{hostname}}/{{ruta}}/register
Content-Type: application/json

{
    "name": "Pepito",
    "surname": "Pérez",
    "age": 21,
    "mail": "pepe@gmail.com",
    "status": 1,
    "password": "1234",
    "rol": "user"
  }