@hostname = http://localhost:8000
@tabla = products

GET {{hostname}}/{{tabla}}/5 
#->OK

###

#version basica
GET {{hostname}}/{{tabla}}/filter/precio?pricemin=20&pricemax=70
#->OK

###
GET {{hostname}}/{{tabla}}/filter/status?product_status=0
#->OK
###

GET {{hostname}}/{{tabla}}/filter/title?in_title=cam
#->OK
###

POST {{hostname}}/{{tabla}}/register
Content-Type: application/json

{
    "title": "Mouse Gamer",
    "price": 149.98,
    "quantity": 94,
    "status": 1
  }

  #->OK


###

PUT {{hostname}}/{{tabla}}/34
Content-Type: application/json

{
    "id":34,
    "title": "Mouse Gamer",
    "price": 149.98,
    "quantity": 98,
    "status": 1
}

# ->OK

###
