@hostname = http://localhost:8000

GET {{hostname}}/users/5

###
GET {{hostname}}/users/25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInJvbCI6ImFkbWluIiwiZXhwaXJlIjoxNzY5NzkwNDgwfQ.eyib4u8V2v0pLa3dkmZ0ERJpjovqWqhuNaPi9V80YSs

###

#version basica
GET {{hostname}}/users/filter/edad?agemin=30&agemax=39

###

POST {{hostname}}/users/register
Content-Type: application/json

{
    "name": "Moses",
    "surname": "Giron",
    "age": 42,
    "mail": "c@gmail.com",
    "status": 1,
    "password": "$2y$10$B2c3D4e5F6g7H8i9J0k1L",
    "rol": "user"
  }


###

PUT {{hostname}}/users/24
Content-Type: application/json

{
   "id": "24",
    "name": "Moises",
    "surname": "Perez",
    "age": 34,
    "mail": "moises@gmail.com",
    "status": 1,
    "password": "$2y$10$B2c3D4e5F6g7H8i9J0k1L",
    "rol": "user"
  }


###

  #comienzo auth
@ruta = auth


###

POST {{hostname}}/{{ruta}}/register
Content-Type: application/json

{
    "name": "Pepito",
    "surname": "Pérez",
    "age": 21,
    "mail": "pepe@gmail.com",
    "status": 1,
    "password": "1234",
    "rol": "user"
  }

###

POST {{hostname}}/{{ruta}}/login
Content-Type: application/json

{
    "mail": "juanan@gmail.com",
    "password": "1234"
  }